version: "3"
services:
  virtuoso:
    build: ./virtuoso
    ports:
      - "8890:8890"
      - "1111:1111"
  entitytypeing:
    build: ./
  views:
    image: mysql/mysql-server
  articles:
    image: mongo
