DELETE {
    ?p rdf:instanceOf <http://fkg.iust.ac.ir/ontology/Thing>
}

INSERT {
    ?p rdf:instanceOf ?o
}
using  <http://entity.typing/farsbase>
using named <http://entity.typing/dbpedia>
where {
              ?p rdf:instanceOf <http://fkg.iust.ac.ir/ontology/Thing>.
              ?p owl:sameAs ?d.
              filter(strstarts(str(?d), "http://dbpedia.org/")).
        {GRAPH <http://entity.typing/dbpedia>
           {
               ?d rdf:type ?o
           }
        }

}
