INSERT {
    ?p rdf:DBPediaInstance ?o
}
using  <http://fk.iust.ac.ir>
using named <http://dbpedia.org>
where {
              ?p rdf:instanceOf <http://fkg.iust.ac.ir/ontology/Thing>.
              ?p owl:sameAs ?d.
              filter(strstarts(str(?d), "http://dbpedia.org/")).
        {GRAPH <http://entity.typing/dbpedia>
           {
               ?d rdf:type ?o
           }
        }

}
